// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProyectoWeb2;
using System;

namespace ProyectoWeb2.Migrations
{
    [DbContext(typeof(ConexionContext))]
    [Migration("20180303080557_Support_Tickets")]
    partial class Support_Tickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoWeb2.Models.Clientes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.Property<string>("cedula_Juridica");

                    b.Property<string>("direccion_Fisica");

                    b.Property<string>("pagina_Web");

                    b.Property<string>("sector");

                    b.Property<string>("telefono");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Contactos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Clienteid");

                    b.Property<string>("Correo_electrónico");

                    b.Property<string>("Número_telefónico");

                    b.Property<string>("Puesto");

                    b.Property<string>("apellidos");

                    b.Property<string>("nombre");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Reuniones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Clienteid");

                    b.Property<DateTime>("Fecha_Hora");

                    b.Property<string>("Título_reunión");

                    b.Property<int>("Usuarioid");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Reuniones");
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Support_Tickets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Clienteid");

                    b.Property<string>("Detalle_del_problema");

                    b.Property<string>("Estado_actual");

                    b.Property<string>("Quién_reporta_el_problema");

                    b.Property<string>("Título_Problema");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Support_Tickets");
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contraseña");

                    b.Property<string>("correo");

                    b.Property<string>("rol");

                    b.Property<string>("usuario");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Contactos", b =>
                {
                    b.HasOne("ProyectoWeb2.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Reuniones", b =>
                {
                    b.HasOne("ProyectoWeb2.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProyectoWeb2.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProyectoWeb2.Models.Support_Tickets", b =>
                {
                    b.HasOne("ProyectoWeb2.Models.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
